version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  streamlit:
    build: .
    command: streamlit run designer.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
      - redis
  dashboard:
    build: .
    command: streamlit run dashboard.py --server.port 8502 --server.address 0.0.0.0
    ports:
      - "8502:8502"
    depends_on:
      - api
      - redis